jenkins:
    build: jenkins
    ports:
        - "8080:8080"
        - "50000:50000"
    volumes:
        - /data/jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /data/rdf:/rdf
        - /usr/bin/docker:/usr/bin/docker
        - /data/api:/storage

service:
    build: my-webapp
    ports:
        - "8080:9090"
    volumes:
        - /data/api:/storage